on:
  pull_request:
    branches:
      - main
name: Publish Website
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📦 Install Packages
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"

      - name: 🔨 Build
        run: |
          touch .env.local
          echo "${{ secrets.local }}" > .env.local

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.server }}
          remote-user: ${{ secrets.username }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: ~/public_html/veille/
          ssh-port: 65002
